# Generated by Django 2.2 on 2019-05-05 21:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1085041c-7a09-4b92-bcce-8779bb26174a'), editable=False, primary_key=True, serialize=False)),
                ('número', models.PositiveSmallIntegerField(default=1)),
                ('nombre', models.CharField(default='Grupo 1', max_length=100)),
                ('id_Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
            ],
            options={
                'unique_together': {('id_Curso', 'número')},
            },
        ),
    ]
