# Generated by Django 2.2 on 2019-05-02 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('código', models.CharField(max_length=20)),
                ('número_seccion', models.PositiveSmallIntegerField(default=1)),
                ('año', models.IntegerField()),
                ('semestre', models.SmallIntegerField(choices=[(1, 'Otoño'), (2, 'Primavera'), (3, 'Verano')], default=1)),
            ],
            options={
                'unique_together': {('código', 'número_seccion', 'año', 'semestre')},
            },
        ),
    ]
