# Generated by Django 2.2 on 2019-05-05 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92002fa5-45de-4a45-977c-74093436d47f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
