# Generated by Django 2.2 on 2019-05-05 21:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen_Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('fecha', models.DateField(default=datetime.datetime(2019, 5, 5, 21, 45, 6, 134396, tzinfo=utc))),
                ('contraseña', models.CharField(max_length=50)),
                ('duracion_Efectiva', models.TimeField()),
                ('id_Evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.Evaluacion')),
            ],
            options={
                'unique_together': {('url', 'id_Evaluacion')},
            },
        ),
    ]
