# Generated by Django 2.2 on 2019-05-05 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Resumen_Evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen_evaluacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 21, 56, 17, 611442, tzinfo=utc)),
        ),
    ]
