# Generated by Django 2.2 on 2019-05-05 21:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('historial', models.CharField(max_length=2000)),
                ('Presentó', models.BooleanField(default=False)),
                ('Nombre', models.CharField(default='', max_length=50)),
                ('Notas', models.FloatField(default=1.0)),
                ('id_Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipo.Equipo')),
            ],
            options={
                'unique_together': {('id', 'id_Equipo')},
            },
        ),
    ]
