# Generated by Django 2.2 on 2019-05-02 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('historial', models.CharField(max_length=20)),
                ('public', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=20)),
                ('Notas', models.CharField(max_length=20)),
            ],
        ),
    ]
