# Generated by Django 2.2 on 2019-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0002_auto_20190502_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Nombre',
            field=models.CharField(default='nada', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Notas',
            field=models.FloatField(default=1.0),
        ),
    ]
