# Generated by Django 2.2 on 2019-05-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0004_auto_20190502_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='historial',
            field=models.CharField(max_length=2000),
        ),
    ]
