# Generated by Django 2.2 on 2019-05-05 21:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_Inicio', models.DateField(default=datetime.datetime(2019, 5, 5, 21, 45, 6, 122758, tzinfo=utc))),
                ('fecha_Fin', models.DateField(default=datetime.datetime(2019, 5, 5, 21, 45, 6, 122853, tzinfo=utc))),
                ('is_Open', models.BooleanField(default=True)),
            ],
        ),
    ]
