# Generated by Django 2.2 on 2019-05-05 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_Fin',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 21, 56, 17, 610884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_Inicio',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 21, 56, 17, 610864, tzinfo=utc)),
        ),
    ]
